train_dataset:
  coco:
    is_train: true
    datadir: /datasets/coco
    download: false
    shuffle: true
    drop_last: true
val_dataset:
  coco:
    is_train: false
    datadir: /datasets/coco
    download: false
    shuffle: false
    drop_last: false
optimizer:
  sgd:
    lr: 2.5e-3
    weight_decay: 5e-4
schedulers:
  - multistep:
      milestones:
        - "40ep"
        - "50ep"
      interval: epoch
model:
  ssd:
    initializers:
      - kaiming_normal
      - bn_ones
loggers:
  - tqdm: {}
max_epochs: 800
total_batch_size: 32
eval_batch_size: 32
seed: 0
validate_every_n_epochs: 1
grad_accum: 1
device:
  gpu: {}
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
precision: amp

