train_dataset:
  coco:
    is_train: true
    datadir: /localdisk/coco
    download: false
    shuffle: true
    drop_last: true
val_dataset:
  coco:
    is_train: false
    datadir: /localdisk/coco
    download: false
    shuffle: false
    drop_last: true
optimizer:
  sgd:
    lr: 2.5e-3
    weight_decay: 5e-4
    momentum: 0.9
schedulers:
  - multistep:
      milestones:
        - "40ep"
        - "50ep"
      interval: epoch
  - warmup:
      warmup_iters: "300ep"
      warmup_method: linear
      warmup_factor: 2.619685
      verbose: false
      interval: step
model:
  ssd:
    initializers:
      - kaiming_normal
      - bn_ones
loggers:
  - tqdm: {}
train_batch_size: 128
eval_batch_size: 128
seed: 0
validate_every_n_epochs: 10
grad_accum: 1
device:
  gpu: {}
max_duration: 80ep
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
precision: amp

