train_dataset:
  coco:
    is_train: true
    datadir: /datasets/coco
    download: false
    shuffle: true
    drop_last: true
val_dataset:
  coco:
    is_train: false
    datadir: /datasets/01_2d
    download: false
    shuffle: false
    drop_last: false
optimizer:
  sgd:
    lr: 2.5e-3
    weight_decay: 5e-4
schedulers:
  - constant:
      interval: step
model:
  ssd:
    initializers:
      - kaiming_normal
      - bn_ones
loggers:
  - tqdm: {}
total_batch_size: 32
eval_batch_size: 32
seed: 0
threshold: 0.23
validate_every_n_epochs: 5
grad_accum: 1
warmup_factor: 0
nms_valid_thresh: 0.05
num_cropping_iterations: 1
device:
  gpu:
    n_gpus: 8
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
precision: amp
