train_dataset:
  streaming_lm:
    dataset_name: c4
    dataset_config_name: en
    split: train
    max_shards: -1
    max_samples: 10240000 # 1024sa * 10000ba
    max_seq_len: 256
    group_method: truncate
    tokenizer_name: bert-base-uncased
    use_masked_lm: true
    mlm_probability: 0.15
    seed: 17
    shuffle: true
    drop_last: true
val_dataset:
  streaming_lm:
    dataset_name: c4
    dataset_config_name: en
    split: validation
    max_shards: -1
    max_samples: 102400 # 1024sa * 100ba
    max_seq_len: 256
    group_method: truncate
    tokenizer_name: bert-base-uncased
    use_masked_lm: true
    mlm_probability: 0.15
    seed: 17
    shuffle: false
    drop_last: true
model:
  bert:
    model_config:
      hidden_size: 1536
      intermediate_size: 6144
      max_position_embeddings: 256
      num_attention_heads: 16
      num_hidden_layers: 28
      architectures:
        - BertForMaskedLM
      attention_probs_dropout_prob: 0.1
      gradient_checkpointing: false
      classifier_dropout: null
      hidden_act: gelu
      hidden_dropout_prob: 0.1
      initializer_range: 0.02
      layer_norm_eps: 1.0e-12
      model_type: bert
      pad_token_id: 0
      position_embedding_type: absolute
      type_vocab_size: 2
      use_cache: true
      vocab_size: 30522
    use_pretrained: false
    tokenizer_name: bert-base-uncased
optimizer:
  decoupled_adamw:
    lr: 5.0e-4
    betas:
      - 0.9
      - 0.98
    eps: 1.0e-06
    weight_decay: 1.0e-5
schedulers:
  - warmup:
      warmup_method: linear
      warmup_iters: 0.06dur
      warmup_factor: 0
      interval: step
  - linear_decay:
      start_factor: 1.0
      end_factor: 0.0
      total_iters: 0.94dur
      interval: step
      verbose: false
loggers:
  - tqdm: {}
  - wandb:
      project: abhi-bert-profile
      name: bert-xlarge-bs-2048-msl-256-ga-4-deepspeed-zero1
      rank_zero_only: true 
callbacks:
  - speed_monitor:
      window_size: 1

max_duration: 7ep  # Baseline is 256M samples, 7 epochs is ~280M samples
train_batch_size: 2048
eval_batch_size: 2048
seed: 19
device:
  gpu: {}
dataloader:
  pin_memory: true
  persistent_workers: true
  num_workers: 1
  timeout: 0
  prefetch_factor: 1
grad_accum: 4
precision: fp16
grad_clip_norm: None
validate_every_n_batches: 1000
validate_every_n_epochs: 1
deepspeed:
  zero_stage: 1
